name: retroclash-lib
version: 0.0.0
category: hardware

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - mtl
  - transformers
  - barbies
  - lens

source-dirs:
  - src

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeInType
  - TypeOperators

library:
  exposed-modules:
    - RetroClash.Utils
    - RetroClash.Clock
    - RetroClash.Barbies
    - RetroClash.Keypad
    - RetroClash.SevenSegment
    - RetroClash.Slow
    - RetroClash.SerialRx
    - RetroClash.SerialTx
    - RetroClash.VGA
    - RetroClash.Video
    - RetroClash.CPU
    - RetroClash.Delayed
    - RetroClash.Stack
    - RetroClash.BCD
    - RetroClash.Port
    - RetroClash.PS2
