name: retroclash-lib
version: 0.0.0
category: hardware

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - mtl
  - transformers

source-dirs:
  - src

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - ScopedTypeVariables
  - DataKinds
  - NoStarIsType
  - KindSignatures
  - TypeOperators
  - TypeApplications
  - TypeFamilies
  - DeriveGeneric
  - DeriveAnyClass

library:
  exposed-modules:
    - RetroClash.Utils
    - RetroClash.Clock
    - RetroClash.Keypad
    - RetroClash.SevenSegment
    - RetroClash.Slow
    - RetroClash.SerialRx
    - RetroClash.SerialTx
    - RetroClash.VGA
    - RetroClash.Video

