name: retroclash-lib
version: 0.0.0
category: acme

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat


source-dirs:
  - src

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

library:
  exposed-modules:
    - RetroClash.Utils
    - RetroClash.Clock
    - RetroClash.Keypad
    - RetroClash.SevenSegment
    - RetroClash.Slow
    - RetroClash.SerialRx
    - RetroClash.SerialTx

